set(SDK_PATH "/home/happycpu/SimplicityStudio/SDKs/simplicity_sdk_2")
set(COPIED_SDK_PATH "simplicity_sdk_2024.12.1")
set(PKG_PATH "/home/happycpu/.silabs/slt/installs")

add_library(slc_out_of_box_demo STATIC
    "${SDK_PATH}/extension/wiseconnect/components/board/silabs/src/rsi_board.c"
    "${SDK_PATH}/extension/wiseconnect/components/common/src/sl_utility.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/ipmu_apis.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/rsi_system_config_917.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/rsi_deepsleep_soc.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/rsi_ps_ram_func.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/startup_si91x.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/system_si91x.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/core/common/src/rsi_debug.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/core/common/src/sl_si91x_stack_object_declare.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/core/common/src/syscalls.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/core/config/src/rsi_nvic_priorities_config.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/SPI.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/UDMA.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/USART.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/hardware_drivers/button/src/sl_si91x_button.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/hardware_drivers/memlcd/src/memlcd_917/sl_memlcd_spi.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/hardware_drivers/memlcd/src/sl_memlcd.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/hardware_drivers/memlcd/src/sl_memlcd_display.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/aux_reference_volt_config.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/clock_update.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_adc.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_crc.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_dac.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_egpio.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_opamp.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_spi.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_sysrtc.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_timers.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma_wrapper.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_usart.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/sl_si91x_m4_ps.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/rom_driver/src/rsi_rom_table_si91x.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/service/clock_manager/src/sl_si91x_clock_manager.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/service/clock_manager/src/sli_si91x_clock_manager.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/service/power_manager/src/sl_si91x_power_manager.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/service/power_manager/src/sli_si91x_power_manager.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/service/power_manager/src/sli_si91x_power_manager_wakeup_init.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/service/sleeptimer/src/sl_sleeptimer_hal_si91x_sysrtc.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_bod.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ipmu.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_pll.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_power_save.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_rtc.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_temp_sensor.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_time_period.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ulpss_clk.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_adc.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_bjt_temperature_sensor.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_dma.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_driver_gpio.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_i2c.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_ulp_timer.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_peripheral_drivers/src/sl_si91x_peripheral_gpio.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_peripheral_drivers/src/sl_si91x_peripheral_i2c.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_ram.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_rom.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform_wireless.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_bus.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_timer.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sli_siwx917_soc.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/asynchronous_socket/src/sl_si91x_socket.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/ble/src/rsi_ble_gap_apis.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/ble/src/rsi_ble_gatt_apis.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/ble/src/rsi_bt_ble.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/ble/src/rsi_bt_common_apis.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/ble/src/rsi_common_apis.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/ble/src/rsi_utils.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/ble/src/sl_si91x_ble.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/errno/src/sl_si91x_errno.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/firmware_upgrade/firmware_upgradation.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/host_mcu/si91x/siwx917_soc_ncp_host.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/icmp/sl_net_ping.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/memory/malloc_buffers.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/sl_net/src/sl_net_rsi_utility.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/sl_net/src/sl_net_si91x_callback_framework.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/sl_net/src/sl_net_si91x_integration_handler.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_credentials.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_internal_stack.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/socket/src/sl_si91x_socket_utility.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/src/sl_rsi_utility.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/src/sl_si91x_driver.c"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/threading/sli_si91x_multithreaded.c"
    "${SDK_PATH}/extension/wiseconnect/components/protocol/wifi/si91x/sl_wifi.c"
    "${SDK_PATH}/extension/wiseconnect/components/protocol/wifi/src/sl_wifi_basic_credentials.c"
    "${SDK_PATH}/extension/wiseconnect/components/protocol/wifi/src/sl_wifi_callback_framework.c"
    "${SDK_PATH}/extension/wiseconnect/components/service/bsd_socket/si91x_socket/sl_si91x_bsd_socket.c"
    "${SDK_PATH}/extension/wiseconnect/components/service/mqtt/si91x/sl_mqtt_client.c"
    "${SDK_PATH}/extension/wiseconnect/components/service/network_manager/si91x/sl_net_si91x.c"
    "${SDK_PATH}/extension/wiseconnect/components/service/network_manager/src/sl_net.c"
    "${SDK_PATH}/extension/wiseconnect/components/service/network_manager/src/sl_net_basic_certificate_store.c"
    "${SDK_PATH}/extension/wiseconnect/components/service/network_manager/src/sl_net_basic_profiles.c"
    "${SDK_PATH}/extension/wiseconnect/components/service/network_manager/src/sl_net_credentials.c"
    "${SDK_PATH}/extension/wiseconnect/third_party/aws_sdk/platform/silabs/src/network_sl_api_wrapper.c"
    "${SDK_PATH}/extension/wiseconnect/third_party/aws_sdk/platform/silabs/src/timer.c"
    "${SDK_PATH}/extension/wiseconnect/third_party/aws_sdk/src/aws_iot_jobs_interface.c"
    "${SDK_PATH}/extension/wiseconnect/third_party/aws_sdk/src/aws_iot_jobs_json.c"
    "${SDK_PATH}/extension/wiseconnect/third_party/aws_sdk/src/aws_iot_jobs_topics.c"
    "${SDK_PATH}/extension/wiseconnect/third_party/aws_sdk/src/aws_iot_jobs_types.c"
    "${SDK_PATH}/extension/wiseconnect/third_party/aws_sdk/src/aws_iot_json_utils.c"
    "${SDK_PATH}/extension/wiseconnect/third_party/aws_sdk/src/aws_iot_mqtt_client.c"
    "${SDK_PATH}/extension/wiseconnect/third_party/aws_sdk/src/aws_iot_mqtt_client_common_internal.c"
    "${SDK_PATH}/extension/wiseconnect/third_party/aws_sdk/src/aws_iot_mqtt_client_connect.c"
    "${SDK_PATH}/extension/wiseconnect/third_party/aws_sdk/src/aws_iot_mqtt_client_publish.c"
    "${SDK_PATH}/extension/wiseconnect/third_party/aws_sdk/src/aws_iot_mqtt_client_subscribe.c"
    "${SDK_PATH}/extension/wiseconnect/third_party/aws_sdk/src/aws_iot_mqtt_client_unsubscribe.c"
    "${SDK_PATH}/extension/wiseconnect/third_party/aws_sdk/src/aws_iot_mqtt_client_yield.c"
    "${SDK_PATH}/extension/wiseconnect/third_party/aws_sdk/src/aws_iot_shadow.c"
    "${SDK_PATH}/extension/wiseconnect/third_party/aws_sdk/src/aws_iot_shadow_actions.c"
    "${SDK_PATH}/extension/wiseconnect/third_party/aws_sdk/src/aws_iot_shadow_json.c"
    "${SDK_PATH}/extension/wiseconnect/third_party/aws_sdk/src/aws_iot_shadow_records.c"
    "${SDK_PATH}/extension/wiseconnect/third_party/aws_sdk/src/jsmn.c"
    "${SDK_PATH}/extension/wiseconnect/third_party/silicon_labs/freertos/src/sl_si91x_low_power_tickless_mode.c"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Source/os_systick.c"
    "${SDK_PATH}/platform/common/src/sl_assert.c"
    "${SDK_PATH}/platform/common/src/sl_cmsis_os2_common.c"
    "${SDK_PATH}/platform/common/src/sl_core_cortexm.c"
    "${SDK_PATH}/platform/common/src/sl_slist.c"
    "${SDK_PATH}/platform/common/src/sl_string.c"
    "${SDK_PATH}/platform/common/src/sl_syscalls.c"
    "${SDK_PATH}/platform/common/src/sli_cmsis_os2_ext_task_register.c"
    "${SDK_PATH}/platform/emlib/src/em_core.c"
    "${SDK_PATH}/platform/middleware/glib/dmd/display/dmd_memlcd.c"
    "${SDK_PATH}/platform/middleware/glib/fonts/glib_font_narrow_6x8.c"
    "${SDK_PATH}/platform/middleware/glib/fonts/glib_font_normal_8x8.c"
    "${SDK_PATH}/platform/middleware/glib/fonts/glib_font_number_16x20.c"
    "${SDK_PATH}/platform/middleware/glib/glib/bmp.c"
    "${SDK_PATH}/platform/middleware/glib/glib/glib.c"
    "${SDK_PATH}/platform/middleware/glib/glib/glib_bitmap.c"
    "${SDK_PATH}/platform/middleware/glib/glib/glib_circle.c"
    "${SDK_PATH}/platform/middleware/glib/glib/glib_line.c"
    "${SDK_PATH}/platform/middleware/glib/glib/glib_polygon.c"
    "${SDK_PATH}/platform/middleware/glib/glib/glib_rectangle.c"
    "${SDK_PATH}/platform/middleware/glib/glib/glib_string.c"
    "${SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_init.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_kernel.c"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Source/cmsis_os2.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/croutine.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/event_groups.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/list.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F/port.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/MemMang/heap_3.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/queue.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/stream_buffer.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/tasks.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/timers.c"

    #c.h.jung추가함.
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/cryptoacc_aes.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/cryptoacc_gcm.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/error.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_ccm.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_cmac.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_ecdsa_ecdh.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_sha.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/se_aes.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/se_gcm.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/se_jpake.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_entropy_hardware.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_entropy_nvseed.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_mbedtls.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_psa_crypto.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sli_psa_crypto.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/version_features.c"
)

target_include_directories(slc_out_of_box_demo PUBLIC
   "../config"
   "../autogen"
   "../."
    "${SDK_PATH}/extension/wiseconnect/third_party/aws_sdk/include"
    "${SDK_PATH}/extension/wiseconnect/third_party/aws_sdk/platform/silabs/inc"
    "${SDK_PATH}/extension/wiseconnect/components/protocol/wifi/inc"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/ble/inc"
    "${SDK_PATH}/extension/wiseconnect/components/service/bsd_socket/inc"
    "${SDK_PATH}/extension/wiseconnect/components/service/bsd_socket/si91x_socket"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/CMSIS/Driver/Include"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/hardware_drivers/memlcd/inc"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/hardware_drivers/memlcd/inc/memlcd_917"
    "${SDK_PATH}/extension/wiseconnect/components/service/mqtt/inc"
    "${SDK_PATH}/extension/wiseconnect/components/service/network_manager/inc"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/rom_driver/inc"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/core/chip/inc"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/inc"
    "${SDK_PATH}/extension/wiseconnect/components/board/silabs/inc"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/core/config"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/core/common/inc"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_api/inc"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/service/clock_manager/inc"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_peripheral_drivers/inc"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/service/power_manager/inc"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/asynchronous_socket/inc"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/hardware_drivers/button/inc"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/errno/inc"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/sl_net/inc"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/icmp"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/firmware_upgrade"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/inc/mqtt/inc"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/socket/inc"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/inc"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/inc"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/service/sleeptimer/inc"
    "${SDK_PATH}/extension/wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/inc"
    "${SDK_PATH}/extension/wiseconnect/resources/defaults"
    "${SDK_PATH}/extension/wiseconnect/resources/certificates"
    "${SDK_PATH}/extension/wiseconnect/resources/html"
    "${SDK_PATH}/extension/wiseconnect/resources/other"
    "${SDK_PATH}/extension/wiseconnect/components/common/inc"
    "${SDK_PATH}/platform/common/inc"
    "${SDK_PATH}/platform/CMSIS/Core/Include"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Include"
    "${SDK_PATH}/platform/middleware/glib/dmd"
    "${SDK_PATH}/platform/middleware/glib"
    "${SDK_PATH}/platform/emlib/inc"
    "${SDK_PATH}/util/third_party/freertos/kernel/include"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Include"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F"
    "${SDK_PATH}/platform/middleware/glib/glib"
    "${SDK_PATH}/hardware/driver/memlcd/src/ls013b7dh03"
    "${SDK_PATH}/platform/service/system/inc"
    "${SDK_PATH}/platform/service/sleeptimer/inc"

    #c.h.jung추가함.
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/inc"
    "${SDK_PATH}/util/third_party/mbedtls/include"
    "${SDK_PATH}/util/third_party/mbedtls/library"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/inc"
)

target_compile_definitions(slc_out_of_box_demo PUBLIC
    "SLI_SI91X_MCU_MOV_ROM_API_TO_FLASH=1"
    "SL_SI91X_PRINT_DBG_LOG=1"
    "SPI_MULTI_SLAVE=1"
    "SIWG917M111MGTBA=1"
    "SLI_SI917=1"
    "SLI_SI917B0=1"
    "SLI_SI91X_MCU_ENABLE_FLASH_BASED_EXECUTION=1"
    "SLI_SI91X_MCU_EXTERNAL_LDO_FOR_PSRAM=1"
    "SLI_SI91X_ENABLE_BLE=1"
    "SL_SI91X_ENABLE_LITTLE_ENDIAN=1"
    "SLI_SI91X_MCU_COMMON_FLASH_MODE=1"
    "SLI_SI91X_MCU_CONFIG_RADIO_BOARD_BASE_VER=1"
    "SLI_SI91X_MCU_CONFIG_RADIO_BOARD_VER2=1"
    "SL_BOARD_NAME=\"BRD4002A\""
    "SL_BOARD_REV=\"A07\""
    "SI917_MEMLCD=1"
    "SLI_SI91X_EMBEDDED_MQTT_CLIENT=1"
    "SL_NET_COMPONENT_INCLUDED=1"
    "__STATIC_INLINE=static inline"
    "CLOCK_ROMDRIVER_PRESENT=1"
    "ULPSS_CLOCK_ROMDRIVER_PRESENT=1"
    "SL_SI91X_BOARD_INIT=1"
    "SRAM_BASE=0x0cUL"
    "SRAM_SIZE=0x2fc00UL"
    "SLI_CODE_CLASSIFICATION_DISABLE=1"
    "SLI_SI91X_MCU_ENABLE_IPMU_APIS=1"
    "CRC_ROMDRIVER_PRESENT=1"
    "TIMER_ROMDRIVER_PRESENT=1"
    "DEBUG_ENABLE=1"
    "DEBUG_UART=1"
    "ENABLE_DEBUG_MODULE=1"
    "SL_SI91X_SI917_RAM_MEM_CONFIG=1"
    "SL_SI91X_TICKLESS_MODE=1"
    "UDMA_ROMDRIVER_PRESENT=1"
    "SL_SI91X_I2C_DMA=1"
    "SLI_WIRELESS_COMPONENT_PRESENT=1"
    "SLI_SI91X_OFFLOAD_NETWORK_STACK=1"
    "SI917=1"
    "SLI_SI91X_ENABLE_OS=1"
    "SLI_SI91X_MCU_INTERFACE=1"
    "TA_DEEP_SLEEP_COMMON_FLASH=1"
    "SLI_SI91X_SOCKETS=1"
    "SL_ULP_TIMER=1"
    "SI91X_PLATFORM=1"
    "SI91X_SYSRTC_PRESENT=1"
    "SL_SLEEP_TIMER=1"
    "__WEAK=__attribute__((weak))"
    "PLL_ROMDRIVER_PRESENT=1"
    "SL_SI91X_POWER_MANAGER_UC_AVAILABLE=1"
    "SL_WIFI_COMPONENT_INCLUDED=1"
    "configNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2"
    "SL_COMPONENT_CATALOG_PRESENT=1"
    "SL_CODE_COMPONENT_FREERTOS_KERNEL=freertos_kernel"
    "SL_CODE_COMPONENT_CORE=core"
    "SL_CODE_COMPONENT_SLEEPTIMER=sleeptimer"
)

target_link_libraries(slc_out_of_box_demo PUBLIC
    "-Wl,--start-group"
    "gcc"
    "nosys"
    "c"
    "m"
    "-Wl,--end-group"
)
target_compile_options(slc_out_of_box_demo PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Os>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:-fno-lto>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Os>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-lto>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=softfp>
    "$<$<COMPILE_LANGUAGE:ASM>:SHELL:-x assembler-with-cpp>"
)

set(post_build_command ${POST_BUILD_EXE} postbuild "./out_of_box_demo.slpb" --parameter build_dir:"$<TARGET_FILE_DIR:out_of_box_demo>")
set_property(TARGET slc_out_of_box_demo PROPERTY C_STANDARD 17)
set_property(TARGET slc_out_of_box_demo PROPERTY CXX_STANDARD 17)
set_property(TARGET slc_out_of_box_demo PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc_out_of_box_demo INTERFACE
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile_SoC.ld
    --specs=nano.specs
    "SHELL:-Xlinker -Map=$<TARGET_FILE_DIR:out_of_box_demo>/out_of_box_demo.map"
    "SHELL:-u _printf_float"
    -Wl,--no-warn-rwx-segments
    -fno-lto
    -Wl,--gc-sections
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztvQtz3bi1JfxXXK7UV8mMfSjJsmR7upNSS3JHE8vWleQ8Jr7F4iFxzmGLL/OhR6fy3z8AfJMACZAACPVNZm53i4fce62N1wawsfGvl1fXX/7v+emtef3ly+3LDy//9e3l9fmnk9uLv56bzZ++vfzw7eVq9e3lv1++qr65+fL1+vT8Bn72w58efe/FPYgTNwx+/PZyf7X37eULENih4wZb+ODr7cfX7769/NMfvwU/RHH4C7DTF/CTIPnwmLjw912aRh8M4+HhYfXwZhXGW+Ngb2/f+Pvlpxt7B3zrtRskqRXYAIqFX3xI8NNPoW2lucYg87wXDSmJ61nrZGWHvpEkxk2aOW64AnYYIwkQQQTi9OnGhv+GHxeIvr2E8F68+GETeg6IXwSWj360w2Djbovf0K+uB8rfEs9MPACi1PVBbOZvrnZQQxYjVujVD8Yu9IGxs6LoyY4y48b1I8+1XagdgzLu35oPYXyXRJYNjDBLzXBjrsNH0wF+aOQiDZoegwbKfb//aPrA92xHMiyyJiKwreeuJaLpiB+2TeZFZmlN3w8DFVYa0MkK1g3cNP/PPbWIyYqHYa+zNIUsI1eJdYnamABibus0UGLSAZ00sAFIoayNlXmpeW95GUgkISQrosF6cDeuGYMt7IBNR2bDHtJFBGc9JKYbphIh9TUM17QofICNyLcCawv//WDdgSwykzCLbaCi0rGpH6bg+JYKqG01REgfYwCub7/cnEpD09dAsw3yKOSapaOBCAQOv3jsg286YJ1tJSIaUMXTBPKvzH2F1b6pchgqdDXtO/jfvyppnERtRIDXt+fmGbh3Yat9v38sA1RfA81S69CKS48vi7EbLslKFE2jwNI49GRDKnUQwch1fEiOzg9GPnchzWOsLA23IGhMZFo/rxLPRlUxBdUbHTorO7ZLjfA/BTIqoBk1BqOnrLJwkyJbX4N8LaElUOId0cfTH+6swPFAvJJh1nGVjG5yPgVP5IIkaePEJ7WsSdpo+JrzJ8ngKKpYkMHaKqlE+1omuMllPVXYgvuaZ+BW2KT7mom4PTe4AzF6Yt6EpyvPkYCQoIPq05yGfhQGIEjltI6+Cro3X7xl2lZqeaHYgbtReERFNFTgHr0ouRn0lLChkVS5e0rIC4ogWBVruS5IJCDpKhj3smKQT6sTmp8VA8vxqT7WyfmluY2taLe/ioKtQEYVLiMHYHQ1GSOADpQBOhgEdP7xGs7KA2Cn5smV5yapbFwUhePwoH6F2Cpt48DWHqhnU2GsECRR8zhgJFchylodAzTYi6uEVqkbhwZ7UBBHyZ1CeG2V4xDRsi7aC3HRvqEbbBVCJaumQL78r9tbMwVJansu5Ci9cybrYwMnvaMm62MD90YxuDc84A4VgzvkAfdWMbi3POCOFIM74gF3rBjc8SC4MFwjKWYS2rJx9VTRIcGeG8TbJxM6u+iX2PyeufadadlQXKIAJ4N+DvBJasXS/cIRxQNw0zD0EtNx0bwPKVCBlKxzFGQCh0q03q4MYUshDV6WRpn88m1oGQRi3u+be2rQNFSNQDpQB+lgBFKtRuHMaEApBSbad8gS07Md6e5dT9U4JCWVjKyPBZyC6kbWNwpOujvcUzUOSXFhHvAUpnQPvadqFJJ0v7ynahSSdG+8p2oYUhS7QVqFwEFpCXAUQaSrZoHsw/etLTBjYAP3XjFosnIm2N9THPyFRhbVoAmqWSBj3zSTPvDSdRJ38IfW0h/cBBRE35iJc2e+WR2u9mkL69WWStJaXG+94+DQlsbvvTfyuPHWG4R33u8/dl7pveTbWe8VAuYYEN7qv7dzI+J7fWwoVoL4Yu9V9+ryK5q6bKkfkD9xwpSuI/+oUQfjxDWTpyQFfhmAhQKLOLeNbs7+khhJ9RRXhgMDPKYgQMt3RqOmGHU9MPLiNvIyNXCxGbBcDGR2A9nUgOYyKjsYFT2Ditpg5e1GfgZ9Tpc7WkI51xZSOr9O4A3vz61+KbcsBqmVebrAaNbo9rKok9ORThcZEx9U96PEjC3f3GSBrRUjAjZmTg4AET5FgxfEdGPVQ0fmNdjMur11MDQWdKwD4jjkDi6QZhUI3WihYirltZUAM32K+KOspBJpw2Ji4lippSGTNizmlmfbUXHkSSs2fWiT+kfdKHWwMXNq+TvaseqhY+IFv8hVaMWnhYqVh4YNqIWKlYeVJCDmjseWzaNGxdMHaNpWWsjYfNim46sTnS4wNjb5STL9Gn4XGAcb/z7SkEqBittXHfpp8Pj94LvDix+d5htAlmiZKoxdFNxZHTbRwMbFOaNiZkAHOmmKQPDNsmRy9gKJ/CnoKKQZi1cvenSQJJY8jQaNyhIaDT7yqUcbQQwbs+cCF1uP2j56Ga5/ycM+bc+KgWbsRrGyju+25Xl6LEY2yDVgKV7vyGuMFt0BNkfpu1W4+MpVLyJNWOJ8A/oPnV2e2EWpiJg2VvzETcz8A7bu8vTy5uKGdYvlbEgw4f2LwPYyh7wlVH/SKP9cATrdtPzcsDC70bSpgc1l5DCNgp7RQ828q1J+efL52ZHNIfMyPb/983NjWkCewNS8PDl9hmxL2FMYX/35H8+RcQGbl/FHz0p2z41vBZqX7cXBs6vNBWReppenF8+NaQGZl+nnk89nz41qiZmX683JsyvVAjI306vnx/RqEtOvNyfXt8+NawWan+1Pz4/rTxOZPrt+qcQ8geuzc4pLzHLiq9iXfLWfMDLODdsnijWdN5wPTgxaFH7WdAj6eXCcaVHQ1N0ddGnb50b19GIHPdUWATgrMz+dfH53fHhwoiOTLj4GSpr6oIN+ZpuAnu2avVl/PbvUsjKVuFgo6Or0jji2HRJa+rKD/mqvJSy7/URtCfTtp15L0JBBiYu5JejIoQQ2b+N7Z8XOg4VyEw/sAfXP6uDrC1g3dYY2zCmi0ekR9k2dxCsvVEgiV5PC6hrWyBHiXdyao9GDPnm+Q7PJM7BHC+uAAchl7rhJ5FlPz4lnEzN123rsfBDzVr6ENqbHuEqzNdpRp7axOWsK1Damvz1aWCfVOZ7Ikvx0s6gBghSJlGvQtdHn6NrxSDViNU1+wGqaVtfCakV17SIWXWnZnaQ49LlCXrjiqpBw27tbOiKpLIOaaxVh1UTIHOyPP4qXPuwzxirmO/GDvgHbyA31plVBZD+aYdl3KKejtrQaAPmq4NIHZ8ZqIN8RGly6myxZ+pTGWAUsIXIR27i+3rQKgFyktpHjW3rTqiByEcsT6SfWveZ1sY2Tj+KD5hWyAMhF6rs+8zcKq+8j0zQirVjn0asBkItUaq09YF7f7D/C/+lNrwd1AlEdTlMy0eQ7XVl9iy520ZxeCZGLWKb9EJdNGeHQR+ZDDCnoXmxdpHw0vShJ0ARPc45NmPPPPnGd4uu2fD1WnRqGKo/1EYBKPGoMa5sb7UBseXzbR1y2t5ylcw+V9u7TrexegGRqd1b2aMZgA2IQ2MC8D71Uj6PUIzQHYTMRt73QvjOzyLHSpQ+NjnDtImVP3BM/g8pagGTPA2Y9A1IFSGZS+RqZ9rQqmMzEwsjyI/2JVTDZ0y1ps7c/QGtkF5+UQypOn0HzqnEyU8NziaUP0DNQq3EyU8PTCe2JlSi5aFXTiGdBr4mWnWaCLh3Rn18Jky9Fh39oRpq3uj5WxbkskLuux2SXYKFy0luAnDmn0JrmIGz+OYXWXLtIueYUWjNrgOSaU2hPqgDJOafQnhZ/eIBt67JlNFQFbb5dI6TVyq9V1Z9bCys7RV2iH4ao8UVA2Px3ni/BiS9YSqeQjqGOgzusAwQ7Cw7tjkaxHUP8OmiZaT4LdrykdIpcGaDFH72y1ScCYogXbxSEe/AMXKoCJAepZ9DdFyDZST0Dj8Pl8zTy5VztWVUw2SNjtYkBG6DFGwf2HTyDDrAAyU7qWXTr3MFt6AN0A1X6DGaWbazsUSjaxO4NcOOO33se7lPM7T4lEKguOQkHiFUwOYj54Bl09hVMdmLPYVUq4VyTSnz3OdTCAiXXLrf+rDjHsOR5sOKmlW+K60+swslJzdwBy0Gb48+EYhMvb5yC9hRrnHxxCtoT4w7O1jAwe4TepODsPABAf34lTGZi95YuGRMGaBUgmUk9ZLEuZ1cGWJUop8SUaE2uj1Vi4HsWuBsXOOgSaMER7xUNfcLeG2Tb0Ts8Qe91PodfUjMFPixFK81iYCYQXKhLtBmVKh01H3t94gapVHmCBuuPsFRTo5hqOr82VD6eaPtCc34FRD5emRcVZ/80Z9cCqjBqsNXp6TEQNm3UGgF5AgfHejjNqdJR8/fLmlPlmSQROzvd+bWhsvJ8Fgwncqs7dG2ZtSBOHXM0Z9cCKnFWkYAYIWSbUeThxL4VWNuBC/MEJNprKdLEPSgsZbSwtR2FHmzmvKLuMyVOxb1cusE2FD2aOdmErQbfgz2z7uhPnIpbeqbQPD2Tgn6spUiz5tzC1u7HerC56+JzI07FPY+5+WDdgSwy3cDV5fAftxW6HJbr2duFo1cH1zZnq2fvwZ5Zp9ahFTt6HbUbsgIbiZk9zDM1g5LRLvEAiPBcQtJQV8k3d1ZZ6bXKMVCWS420Gu+GsS/Q17kdTJpV7YYJq3rdw7tc1uxyPi09S1Tdu9eaNNyJGDsMT0DPt6DSEKDfPgUH+8EdDLmr+90y0KPBD9iw7d300fPVoGfIeTpRdKhWnzs9efg2kM/qIZ4X8z54mWuxT0kKfA/cA09CTsN1qMu1TA2eVeKZAh37cbbIzzSmU8JjP/LleRrTKdCxs6nzn2tMqgWS/YyNPtMaAinuhGnAj/SKhyKx6qDkCrPGfbjWfV8HJXusbpWdWF9uLYyKM26hMUUPd6NpmTIqtkDHnr0o0WrnmkSpCZFvJNeXUwmPayTXl06Bjp2N1oXDXTa63R9DJDXt8pgoDm2QwBFSrzA6IkMCVHb/C2w1OrBIotdAyMEKAkldbZYGyLwaGLn8ZY05cZ5RbHqi+rLqoJzkL2vMro1ygr+sLzeGG0dI58AeHF0O7ZFIlfDErZ1RfqA9bk8iHtwYeHD8IcwkulcKe+TISOZ1uP6cxAPm1opQwOeSCZNLExgQT70G18FGKS4ypTTVmFMDHCuptFjw1pNVDx07LShHQzoFKkYaGhfNtHLJUtfTjkoFioFEfTpGr+rVxUWiwr5DQ19+IvaKuBIsNyy3jFEtOzVwcXTwRbVePOqMyqkHkJ2chnR4CLTHAt249NBx09K0zhHw8VLTlhMHGY3r3rSKp2fRcJdLliy6VUAkUWLicop041CC4nWKNOLRxcXlFNF/aPtKVvIU2Ls4DMIsMZPQvgOpwLl0RSGXrIPLSSDcdkFrqEq80K5eDSogyUStCllDlVInfeCH8ROlGjZM51ueF9rmOttswKLXyVWWy5EbfWB9O7EaA8RxEMpokliwDkbDQNptsMKmpAnm2jRoeLklUFOrIElpYNDOgZx+Hoo13SAFcYDOaaSWvWTUS2XXnG+7ipGRsrkL6NviVCxs6Wv4rbmJ4a8PYawh3zG07JxLzwri1JNmByBvaaL6sI0ttHlq7qzA8RY9FTtanBS4PC4vEmbHwEE7xpYea5u0xtqBqco561YrDYaJwkKFS0YAKKLea8lzEC4na40ZShv4XduPxv3qAkrkBlsdOgQE2uhgIlqHxkGDgu5xIJYwazFu3Nh/sGJgZhFsBw5t97thjs4XuO3oULZdJt0HFdDRAid+qEHJszGcVR1og1l3Wv09Jfv8M05H4v4YCTZtz4XGILmYGhQC6mARyrynZQTNdoCuJyx9ioAW66EjpCucE3lq5BCNMB33jCaeC2yPN5p5iYVTweAaUjJ0hQGcFgeLXqraJUNAxkMIdbrYFK4+LXQAHju1PKxPO0o1LHYquzApFmY2lq3FfkyLUh8eOzU3TDVa5W+n6WxBY6eEb3SzQ0+vUW8AHjs1dGGdvn1gDx0HsdRKMw0ZVbDYqehZ67gq24O7cc1ctkZEOqimz01kbylrtR5N3U0eW5SWsXC5Thyd3NH2PnIHHM+SdWFRPSea9N1yrknmMHOdBqUhwmPD0whPbTr3AY4jk2imnktvhmNzx9l70ZRuf3Cio0Nn3785hnVhWrdt1Li3UDArYiXdxcBy3GDLUq5lwk0/81I3/xIsmQWkskrFwhgAOd1IeB7p2xmTZ4SUM4367sPj+/1j1HTNwI7wZFUHW5Zki+c0mHICHHfrer4u+JggSkYKaaGL5eCYroOlW2yrI0J9nGzDVeRZ6SaMNWXWAchHySwFa8+thZQrnDnTl1wLIRMp1AdX3YauvHogGWPomw001LS5kXHyVMilr5FjqZKDN8hJOYKoz0mWtlkmn2lxrNTSZ/JGJtXGyEpMm10WCqnB7RYCIf9QXzI5NkYiocZVLeSpYtEddJS3vhYbRGQ6TYTP7JAbmRDncTekGA2BOyt2cBhPAtIs0pceHS8rYc8K9DvkSyFLxMpD1AEbN9B55OqinOA8a8mNAJKT2tJ5NxnJjd0X2XGd9dkaJNEa3CPkX70hPiY87D3qP+jcJVcEArSc8l7CqY3bcdoZloaI+7lrK3HtBQ5WlDQNhKKc2NARdYuMyGWxI050MiznmMhVaXyWRrZBw25qWmKbfHNXvoNlahkuToNpO5TMRvEG6ACJoS1OIvZFwtvoBMbD2YgsVM7u6eCp83cS5qXR9nGy9FDkrR8iv0U65Xw/p0YwypB75CZdfd15JQAp6j8oV8VOGMOXORVZXt7WodM898k5fqNP8oEfFhv6TSMqfVzsbGwQp7DC2VYKp7NpGKvKZcdMiwiQgZ82PKb5U2y9VX3McWG2ZefVAiTHiwwWiNui8W6cNuXyX9AHTqAR+gIMC243UuqzMIBvImJhoBl8LuzKfUYGAnweZKDszMY4dCZPkvSokzU7ccgJv0idOi01GCXyoBKtuIuvFRtN2AYF2ViptwIhkyyKwlh1NRhl1EcnYQSDtc5ZL8cc1f0KwmChwbfcPLPP4mgbOFggH8F3j7QAXSEZbh7Ag1KXBVxjGIaq8swdDSr1cF0b6pPqIbKL82l8PMyUXQVMAZmRLvadNAgSciJMmtM0jpsrHvLwufdqKtPBIWcy01Sith7Uh/x7KMbG8qVSNIxAp7mgIpbO1qEVO0MLZ/k+38z1svyWRKhJUcXHuqotyupi4gKAhBpfy1dTY1oE63soCwCD9bx6s4h+yGKVeXDowPtwxporvsx8Uav3QIxBdg/sxRG3MIwBjh78xQG3MIzPx5avEwlPlYDeVJwuXyu6MMZgfwcL93hdDOLHxjxIbHBw7A18XTOpPcOXIy7X6Ckn9cY93v5w16VlOY6Luuk8L666VBEFwaL8iSiMQeC2n7iJ4mO1bdA9BCOAFe8IdMDSF/97QxsA4N3egVLHuQ22h2AEsNr1/g5W6tI+rQdZAiWllo71pN0/u2d/XejtRVacNvP3d49kPiQI8ozOF0lAKYt+CddJI3xFYkfcIGYU+HFXTEcyUPKtj35J5KbiZEJegmAFnYaRa0uNJmCCXcNgBo4b5uK4SxQssGHRyL95cBR2CwUD7FZ+zTwiv0y3vySPEVjcxLBWfQhVcDiJRNnac5OdLkQacDiJJNk6sWN3vehgQAXESSYLtKPTgcRJ6MkFntR1Qh4qFRg+EprAZwSe7CwnfDAtG82lFh1B+kjY4S/tI3VgsAOPoYrY0cHuDSTM8JeHPQL3l8RfpF6UevmWXsqMHmMbjoRNGaZtmX5gAY4gQospkWs+xNAkcvMvkMxVkm7u2NCRERIqNSlJzyDByoCaJoJ2sI0lPUSfap3gRuIKAQtntGbQR8RSWmoOu/BxGMnfTGxFWtEggmKqipOiJKBKL+tdM0IcOEAch1IP4ZJMVOAzeiBYVwUWK9wu8j4armUkHdCXQDiXknSAXkPhW07SAjvDijNhMWdp6C0kDNC9UGr6CRbMBYSZa2ALkxiBxklOm/6TCopzjq8PDUbwndn1wvj7aNgpaFOXSHj4lixwmjFNaLTwcK686MOAD/wdkLq1yoG9QMK/cKQH/AYaBgr3IE4kRx2yYG/AGFtCWghpqZtn/520XuRCZWZv1ah7aWQMQJyGc8N9q4NHHqwXUfgAp9Opa9+hDEGmHzrKNiqatI2SWzuX5wDC2QFlw2EQMUjCLLZBQg+CaBwR7xZbp0mVXlr9wSoC/sqWexatomA0kRrjgAwGLlHs3qOz8ahbRJ9K7qjHuVAADXJJUiveoD0k07bwR8swIMGg4/41i4G5trzU9dF9c8shpwKhYrctJGEhvG3ldIy4Oi2JswdgBGtZ45eC2tBPRYrO0IB4Qav2AYxgXc6qPf1UpOgEPE5+ugzQrnq6RfG6d3PUWcq0VCCM2BesFTQcVOT+kwPu79y0O8qrxz6AZBT9chYnIBirJc4WSVhuTKbBoOIGVrQQ1IZmg3mmtEv9bgLQBhkv3MrNGlBTQUCMSh/VvDvgwSlMGHtSz+F0YLWVUrFFcXjvIlluIHVBvoOuq5a98MN010kN1+LjBg54XCEdathgOEZbK5VM68/2H921gDaMvYPD1f7Bar/iPR6Rwn1OiuFAURr6rqC009VueOe0UKVi+MDF2hU0aabgKOSznFMKkwOhd39QEJGUDcJzG5/AWmymVnJnxmDrJqmo9NpkqKOKxw5TOXAa6VlJko8SwlYgaYYl6xuzrVqUVIXDtoRvA1HLS7QWW6kYK1b5TYStYaD3IvhEaiNoKRmDEwvaI6NCicc2vdBaaxoL8wEoQGoVI1A82FfIRVJqGLOJuHOzVJuQDsWOx3KNH2vujRhCVvS7NIqVepKyGcOTRKijipm6VJm2rFWMdxzoHyl4FHTXHK1wO4qYOhKZgGoVI1CeEpSfXlDcPg1MQwlLvyYVS6lh1lbk6eXNxc3QXOEUVojh/ccLYqhpd+UaN0RJwzEmYSCkRgHG6OsbzKCRvy50F3wcHXW3uxuU/Ss6JghbpOiBkoCsrYvBZltb9DSRaq9C1TAo3H+JuiVvEFND0yAkP8pMK/bvj+VjaqkSkGvv+vbLzYGw1g+HYSkmwCg7daXQNVgwYYKjDBRgamjiz3Z2g9efhg0MFcCxCesQO+Y02eRAjLYu8Xl+fNdxPIAuvhsal7aeux6umY7vjB3JctwEMn0aO9gDJZk+8D1b0EHYyro1VQPxMaAio8BktJUyH1pqwxZct4l4fbZ8Tywl2CGw9iPJBsf/KNQM9hXoRRVYSj2jYNC6pW8psU9H3Tg0241tT1BYGQO0Wt04NM8N1AErlY3DikLvaSt83k5H1tA3Di4GdmoFW4Ul2tI4DlDKNJSOjjYlJfRecrvfqvca83Rwr6IAS6mHoYsIPVGHDll6iFIb/yi1gbMh0tHuLiH0nhlYcRw+mEeP7yRXRozKoCkeN3/+EZRseeY79WhbilnRZv4axOb+0ePBnmq8HdVMtagZdOGLPHVIhd1UM7A6BTsMnNxXMpqmmiE0kY9sLBtMrWXWchn0xztOK99aPSwiW9jlZxVbjAqvCzbkC80xWsoVW0o5brQ70pA/UFeKt8wtCEAsPDyhh6apZ955j/ELEdGMGoylGWE56IHlmG7gil59LrPi5xoaK+JNfQzZldHrdyAOgKCkcmwAa438LgDLBQtNO4itlh1adX7opj4+uysEWGsUsByZeABEOB+IgIZSyZJVDSsF9Y5NU+VIkbmN182dqNPn4yhJeiU1mdoc0rlVsQBNlRwloAphV6fkQ28ojQM9kJCcGbg/Q2I6pZh3BGMLsuS0Nb3CERmeiGzQOqZYnUzMIdeHVCkBiz10dhxm6FouxfiaakcQOiCKAQrLdkwHbNAgIi4FATNeOogR9OAenYjYQrqRasxd1SNIP0IxaO9EMcqm2hGE4sKvmNGR47F6yHyQJNYWmOtssxHVATNj7CsfQxtlJr5oXeBEnx1tTzkD2iKF3xJYm6pHkKIbMq21p7ovbaodQxiHv8D+S7Udm2pHEH7PQKbagJXOEWwJ8KOd6tZdKx1Dl1o2us8XDq2qy7eregTpDXr9cgmgHc2jFo2B5S/Tqfd0jyXDtBJBwSHMEEuVLGk6VRd0rXRaBtWyTyU69603L4F/aQVbwosdO+yAFZlvxEzgR+1Q4jcKeEatnVBcZJP0qP58ekqh2Xrt5PrSPL08/Eh8lzBkqjYJpGGUGI0SQN8qRKy4j1NUl+mAKxQk1PTSpNR8huicarqmpqia6gYXPlpTHDXYuioH8YkLrB7FRYqw7uHJPR01gCpdw0tXrXFODbKezuGIZjjMqapcla5hRPngpghSpYx/ZRWHt44to1FCRqlRuZJpY0Vl+GhL6zRPghZz3OFX6hcXeDxGsYz37Woeceeq1/0oDAWt9HNDrXQzlYnwpeidFTudmN9usG7s3vfyAbQjh3G47JS9odYrXrK3/2Z97Oz23oxVMXQzOFZqFmG7YgqvNIaRczZyHXiHpgHOIGpXUnydjAbNpfmIOyb1/q2JUuMnkYWiy7PUDDfmOnw0HeCHRiHP6GvyLZc7YHJQVSmQoAu6jKZoZg2ZBI0o15JwlU2hBJ3oF876O1p2O6o98wvGhSpsi6VZVYLijlyCZi/chkUQNffEfVB1VzBBN3TNHB+s0HkIYWobMgkaO2+vEi9aC1ROFl/gaF1cXwI6Axsr81KIwbPWwGs9wXdWn4Z+BL9Y4xtWUQ2NncO9vQPrw94K/b+TvaMX6NGbN++qR/v78GM0uHa/9e1sZcX+6mHjrxL3Yft+/9jf39/3t+nagp+kcKC1d7Cz6X5nh+h9lNFplSSrTQyhIxus0FovviQQhUgF4S38/hR9nwOBEuGoMSTLuVvh5UT4AP73hyrHzMp8/eb926OjveP37+p8M+ARewbOlZXu/linv8kL3Dg5v4QzNSva7a+iYPuD0XqbT8LBVAnnH69P8/Q85skVnqTNF4T6qvlSYAdUV78wFiAR128BYkI49Z8vBqDM6lFyJ0AU6jLRieYqN9REkZf/dXtrpiBJ80x5k6tlR87kytmR80aQnENBct4KknMkSM7xVDlhuEZtw0xCe4YIE4V4bp/Q9ikalmLze+bad6Zlw9cSkXJRzt/J/RQSiEaNBDr6Fhzw0cg3X1YC8GUPkwVlaZRNp4S/Nu/3zb25Ig6mi6jdDgHjQJ7fxYTzscmdUEPELNO05MywTy1ncn/YECGI0uQutRYxuTetRUzuSAsRUewG0GHI0jQM4B+wuwGOEJFl7EoMbODeixKKr7fJ24ggkbhHzAZamwPQrcUR6qP++IPR/Ctfgmg5+vDZD0bhKMP/fvnq5c3F5dWni9OL23+YN7dfzy6+mJdfzr5+Or95+eHlP/8FPfzM9VI3OM81J99efvjnf79CkyU/hFaDf24sLwGvqhdvyvsBPvwTuddIdxVpdVpN/V5Vv13fnptnAMV5mnAC0P6tvPDCJnyHzyHkBxAcsM62xJeKY239HyI3ID5HmQ7RPMdsWY3+Thrnq4GtX4vsQETpAUDOKp5TmfeWl+WBSK1X8jseiiqPAv7MdRrs0QS23h6glb/n+NbwC8VK2eA7+dUTvhXA9hMXr5r7TC8/WHcgi8y8wg9ryUM7EvfXkfcyLzLzOOziui/Gt7Fl8X/SbVvHeFPewCsaKFcWuoOoWdVQG/FDJ0Mb+R++vfyhaHMfLi/xwxePvhckH4qnP377hpL4ptEHw3h4eChnpJCPkSTGVTGvRVfVAPTmi6Kp4c/SOMsfug7+O7NXud5VAlC/kdlFq+uuBmxtG38XOX5L0B+/4X4DxzOgSUcCJ+8pukANv7X6X+ifBnqp6khKUn/ExinAQdpI4r9fze1DrCwNtyDAHQWavsMpWpCWrab80XODOxAjH9K8CU9XntP6tcg+iL80bSu1ipvu2q/k+6s7K3C8fHNu6Ofe151WC2tvACn0xVDeo8hrtx4qNtLL5aGX8TeLRsklvfNNT0+7nfVlNn9v2ECjZnMLfHQSATz7hgP/D62NRSjNOPpNGxsXKi5BauH72/QydOOyI/KqHpY1sm5Hfoe4Mjf6ajHnGn2PsLo2+k25fjb+YrFCNvpicw1s9GXSKhf5I9I6FtObA8VBWotievOQ+c23zG8eMb95TH+TOmEnv86ywsP+ZbWGQ/+EtEoz9nZjHYb6anOpi/JStRwz9Hs1BR9+6WDopc46x+hLIzpJaxVjbw7UedJ6w9ibAw2js2Yw9tJAcxiZ9zN8RJrZs3zWm7szfNSYnecDK+PQnG8uv6o2k1+1Ns9fdbd+X/V3Rl/VW/uvWnuXg4PSfwau/wxc/xm4/jNw/Wfg+s/AVQ9cr+gX7MwKshuSy5eWep6kIiXyPCGNPNSTBYV1MuSpMlrJi6cKaeev5pAykER4spRG2l9uGcRku0xSaJe2TPm4Snkw4eO1O1Ut6QKkKWLI9+hMkjQLBmdrJ1/pMuHT6uqTKd9Wl5VM+ri8/YX/49E7pSaJnF8Vejd2TPiYdHXKFDFh+5KOCSKq2yOmfFvlP53yceMKDf7PR290YRJJzDs37ctmjjgOCZ1cfUxfDiVYnCagToo46Xt6tvLp4vJk4pO+b6a/nCRgOKmqGJGtzKdiRHaSk04S2syDPk/AVOO3sp/PlDAbQyPb+UxBdW7yuYLKFMYz5ZQ5yWeKaSQQnymplet7pizOkYk1Udw8Yd2cblOlEbMIzhNGSvbHJ3EoKeV8SXX2yCmyyClK50uqc4kOyZp+AFOoVIY57JSDu9PkEXIRzBLUTRwwSxgpe5oQgZ0MOUJkss3MJ+UOFCKQntxPiPhuHj4hQllmyzMyyIkR20v1JkxsMyubEKHNJGpiBDZyngkRWGUpEyKtTismRlwnA5ggoZ0cWEKklmmrxAir8kzNEseywDEzwZEk0VUqIjHy++mqZsmtctDMktLLFzNLWpXjZZ6UKi3Lq/b5+1e9g+P4SQKKvak3WNObFVRkVOG4iYFj6Y08rhA7tnHi5gH2AkQQ4/gnCIRu7TZyw7m4oBj3wBYgJXrwBUj5DmZbGocHi7ALnDXE6SzToOlHXXdsRhGdrRzHwT6Y1Vna55WTzwJQW4ItbKqMEEdGp1MxuACAd3sHreU+bhnRrM8nGqCYSJZfsxalA/LZaFEdUNS64dsZ3nY17J0bYVhrKwGcpNgEoxhmKYLhZLq1PylQbmvLTqDc/EXBclHjtu1IDmgkHMRxtXooUm6U8A6KXLJj6CJsssCWIL1Yy5GCvjiRJqOmFGfZ7iPRcnNz4J8Fikb9nXt1+RXNWbf5fzlhCp9Ffga9KzcR2AXSdPVKGx/HFKsX6XAAiPByKg53Ey+/2R7ESi9CporSFyy7WbHEiK4H4tzs60xUA24M8eU2tUjBdU1BkEUao1ygbpwvDde/5GHEtmdVu8wCtbX38WcLxudOy3EwS7oHU8XJD+BrKFQwjF10akyGmrKcKarmWiyPVyxW580iejGPHTvL/yh3AfI/zdOTz7P58SsV48tw6z2//fMiSs3Lk9NlFF/9+R/qFX/0rGSnXu3FwQJGvjy9UK/088nnM/Vab04WoHpztYDSrzcn17dLqP1pEaUL1CWoVVJXrGCIOZfWnf8srbpL6xyldYBw6DI/nXx+d3x4cCJHg7QODZWiFE9OWvX4enZ5IgcyliwHM+6l5YCWNwCI7OTLY0pm+SA/gVXvUdRZV6TrbE0zC52iyqansziPhXgWB7De7x83jmMlkSuPcEN5pVG6NmReKlXZdi7KthXErUhbdbJOlNYIxG60A7HlVXpRSVrZoxmDDYhBYAPzPvRSUbP/EcW2F9p3ZhY5KOuOZF1o4cFy5i+ZM6ixbXEtcEgNSm2dH5xXoS1WY7v5e15MWuavYDKocSwlNgObLFHSfgAKiVCiKNihDGGOuXF9FfoUqdlGjm8pUSTSCRjQ4x4oqeDugZLm6irpSMPI8udvUzIoih6UVOrvQElV+66oSiM9eSixCm1xIN3JwmpUdTyJ44bilr8HFUEfWYkiNSNe4rtq7KamFSWq9OAgQnWazB2wnDoMW6rGVsC3VE2Zot4B6SnPUyjRl1gCYugYFN1b4lZBBtQ8ZPH8KKQRPXVi8EMzklr70FoHfelB4poHUtxaepCsq1x6UKAGzdIVqEETWwVq8vmmAkW5T65AkcgVyyE1+bCoQFPncIhETXiQUqSnGqRU6MODlGRFnV5dlLY49Mu9nWrWadl3rsBZDUEFemR7d+IGJ5oOgUueNBXi3BOKBrGLgzQlQhcGKUpELtJRVIhdoKMoye9VSKx76cUicgWIokLosgxFh8hFEooKfCTUvL7Zf4T/U6NMzJmCMVWN7CrSlAidPg7oED51pOnyoiRBI4wMReWw360IoobkMkVLPsEpbm9pz+xaPwnjOKTYXUBzy+1pK5Zr6yqHkALNrTt62qXc+km4rUmKXb00tw6ES4bRqmxt/nKLvF3ZNNFcXhbVyC0lDsVgIrFGti4pGnvJxpDC8nyR2El3fkLMA/d5DpDipLu4dUaSfCcR7DGQlKBDjlIVRJ7AOkCSLxu/+AkCUU0coisTQqgKBInAKCKSshhshe49kXWk8FuetB+TtAjcbyLJhw8iFSWCGrqJlosk9ynivWmSlocHR9xSSlNBnWREXPQnST7uFWUqQL2iVPl1ryVTjawhtlrQbjQ/qXoazU+mnrr5idKSBe7GBQ7KU1DOOPKfTKGrgAQ1uZ8lMoqXqmT9S4qrAoitNIuB6A6ZqlfkUgpdicriEhkjSFVS3S4rRVVrdidyJ5eqhFL9pOsVucdGV9KoftKVoeonXUld/USrGovSkNKGWZSKSsrEq7vx+yLcG7/L6NnG9m+79BXUN5r+uS3rwY2BByeghrVbmy66hHFjwXcax1vm1q8RDYLyt41pwWaUqaG6X0yK9FCqdaK71PS3/ry524gOlDZHpnwkFLYlszrUl992LlOjZwVFAxGxvs2iDacrl9dS0CQCfyFPAVqqfnh8v3+ME5EpUDPfIaUoKud2aO0ZVTz/EKVAk9EZkzSF0jShPLfFVRMKVJjlaxJ1Fd58Jl/HfPdzUEu78YhRkzwF9i4OgzBLkNQ7kLZdrfyZoAZEUNbODpcrE8IMpRevtmw8QV1aR2ieJlKKZAkDS0tFKtS3I4qWZZ1UtnFkWUaqWcQ5WC2pqTsz0WRPbN0ji2yV1RYBbDtbK5qfwHVAeprKEp9io8iQ26x7wuVLFZ5XQaFiW1VQiGQQx0GY5+FG/yWmXudCW4Bz6UIgb9zYxzOlLNrGFrqXq/0gv7xBoSohNtuFSYq85OJ5w2EyAzsy0c9iOLm2H6FyCUBqRvXNfqKlCjEKzlP0PU2babrx/fWeCz82UbLcNcrLu4EzGPAQxvO2iVnVClz1GdHEeyPCqC5YQmXXJFpujt7mvoaCRzZqeBi6K7IAOnsLEgTjxl3NiiQocMNU6IynvWqNEhrYoSe64tfTp8iVWnE4L2dhFyzeIPhOJJGLWT7ww/jJ8GFXCYeS/G4oQV5J3t2XyFHPL7xv6avAL0gVjhvqNr8DytxZgeOJ6hMKhYVj1DWYyDJpqCj6zv5QKVUfyYYSFObKkFo7Bg4K4LNE+dw0RbgbL658skVZsbWAtU4cwa2Iuj4mzYUaUim2px/QJLB7HtAio6gIq4uC+4m45wyKlNvyp4QITncxsBw4s2icG/AzL3XzHwB7IFzpzhhorG2Ou8wlSJUwpzkNCOVuMAOyGt3kfGkT/Vq6QL4W25ZTTJyLspxWG4rqi7GsrcS1J40rdJkzhuHyQAkaHRq9ERySnDWzxehCXPh/R7AsjwTJgqLmSkpgy+c4406Twjctokl5Yq+WFBEZR8ARQURzLGgsBFYvzKlIZNnFuJNkEb6clxd7va7hNRc1RMnh7Cta0qquoomL136wkqMG3D1AGUyobHRREzp/BqFOIFQc972fDDKFC5wwvtCkVtWnnpDOrTz1BEqgqHIIA3EKydtWCuCkJeS4uIxZBRzxNi7000RKZh55Y5CEWWyDxGgwTQzrIakWiuvnqwj4K3usOxsXGUHfFhn0DjxhkejfU0WiuwI3LvAc6B9gYZME/YpivdcWdIl9tFA6Q5RtoT+nf44tJEBEadspEoAVTf7Wf4JTkTs37VabObLmcEGNBcSzDJqLmAUCT8uaLUqQKAGgnC16OqfKo9EBRyJwCNilvmfsgOeFsAvzRg5Cdj7zwu2Yg9z5Anax927ihsHo7lr9YZju8CDogMcVEjL8XbpzY8eMrDh9yrsl5w4NoPj6KfQ32mRguPSYRcwvISw1xokjs7xfkrHNWGZRaRi59oijwC5s3OlgkgXpscS1sMiC1W++EGannlNYGZZRrrSKFS6w1iU7ywkfTMtGy9wCSqWQJx6hmJbREIaPPwiTOOo7cciK4fexI6Aw0PGV0eiOIUG/JP6Er8sA43IZtFhSwU7yjIpBEpvnIJEitIrEni0TTQhK/nBiYEUuW35NVtkMoc8kUTj/MHkwmy8LN9f5YopBTIAgPIDNk1MPXrPkMC/YcAjqjTcCBePPxQmMsrXnJjtxApNsndixu55ZbVtBS4EEoU9oejxPXD5AiJBRjfgiZM1v7J2Rb5IsPFgxfwn7Txe+YuJedBMDOJMKO3t/cFJUZPVIXfsObeGZfujgGvHfUAn878wD315++PbyBziz+QUq+3B5iR++ePS9IPlQPP3x27dvL3dpGn0wjIeHh1Xeda9gkzWSxLjKX1oh6gC9+WKduV7qBvizNM7yh66D/87sVa53lR+yq9ajbvCfYZaa4cZch4+mA/xwtbVt/HXk+C1xf/z2LXjx4gc8ziMXIXkRWSnqOvBbq/+F/mmgl34wOtT+iA1cQITkkcR/v/pX9ej8EbsOCfzpn8hKMYRxDxz458byElB/e5NP8Mr3tLCmAzZW5iFbwi+2yTM157eXXdyJF601qrSneLAqZFyFSfoT/Nh5ptbWxqq/EXt+e2llabgFgQGrrY0DH4GxsmO7uhkj1qkDzuzy+4XM/d8vX728ubi8+nRxenH7D/Pm9uvZxRfz6uzy5uWHlz/8CRri27cXxUzwx28v91d7317CJyCwQxSLAh99vf34+t23l3+COqHSQid8JbB88COJ8WleECTCSDSUAOc26dONDf8NBZQSX2IF8AX4/3/YhJ4D4lpLXritd8o3XVjI1Xvt7JN2dQwNvgHrDMoXA2BB5cZGDz03uMNPcI3LLTuqIA/NyS+hlaBi67lrqdCrfCz943oylaF8p/l/7knVmF8xjQ5pqFCDWa3TQBYnvJudOx7mveVl+UKrSA143zgGWxTJ6kipeaUfL7M4iCl2820CqXpR5nUJ8j/COcf17ZebUynQ8UETCahhn4j7LnR1N1hnW4Ulnmsy9+XowqHQ8L9/lWK269tz8wzHhqIr3EUzaCb6zuLqRJ8UFWkcekKFz+/FfzByZ6L5qFjBvrLSHfwzi11EI80cN/xQelVG6XLksipvC//1Qo7ndAt8tIILxPpOhcPM5jwRWhbOU54bv3J9a9P3y2NqC26cohCvqhqtUayZnS/2KtAi2GxNZ0qBijw/vexyL8bqxkEkxRpFcsQ9UYyemTfh6cpzBMpGw8RpFWEm2lDVWqFpW6lV7J+LVADukXBJxdwWPrFEpw4VVQ+rbKwoXrgEqYU3qpcZMOBLq0KDi5Znfts2Z1hMn2zyKqKJaPTey5bjA8KbxEI6Ob80t7EV7fZXUbAluks9I6NNE/CYggAZz2jsl8CnFvRRUGBa4EYRSBMD579D+Ts6BmlEaeWAjS6SfrseJnCgDYEDLgLnH69Pc+3myZXnJunSPCiA+OlYUaQRlwoNPxGoqp4ghbFGpIjI+AniLkofVjWcCVRgJ6wTlQoOPxWAAjKi5E4jOm1I/JTQaiJaVq4iefWhRobGSPHyv25vzRQkaR6vsfhgSsYzjcziAysZzzQybzQj82YOmUPNyBzOIfNWMzJv55A50ozM0Rwyx5qROeYiE4ZrJBXn3l2YRw8KOwUTTZO3T+VJw9j8nrn2nWnZ6Bo6DXgx4JtBFp0QXHxeNAKMg14ahl5iOi5aR0MKdWBGxsRNCgLCW0jaMGoBYqWTpVG2fH1roOACbt7vm3t6oG9A4aRwoA+FA04KNy5U6dpu+qTRSsgAKEZaeRpB07Odxac3PSj8FLRoJGQ8U8ho0FzIeLjJLD7d7EHhp6BZ5TqYU7kWnzH3oHBTWHye3IPCTWHx2XEPCh+FKHaDtAq+hNIT4GhCiQ5tCkUffm9tATqOBNx7zUiSwU2iiQ+n5fh0I0mANoUinttliztudEyEyAfCdjnhUXfLmHzkjWWzuU5pNLDh3Pkmz3NJfZ/yVX7uYuQr6rfv9x+ZPqUI8O2M43OqreIx1uyydm40URbNRuhkzAyBFLHu1eVXtFxCOp0hUoUTpiLwtxW1+gaUKza/JLyMJkbRuDZXPzCS7RXdf4FqiYGKF58nrcxnVCwNKhBaJyeEvhv5WXVTjGrKLeWiaBJ6xqUFdUajvJCrDHsyrd7VNd/I/aEVjVyK2HSVCaeD719N0NWR5iYLbNmECOqkUHIAiPARufKqQtmkegrn0BLQEPujSyBmXOyZukolJsvE5V1wlSLhNWZtJaBO7yWTR1uTcCLt26xlEmlrktKGbTtqXIUou3a1tUnvZxUw6qiTQqnlv6kg1VMonBaUXl/cI5NOS5EMGmoaT0uRDBpWkoA4VUCjViSr+atrJy1l4p3gppctmU1Xl3gy+QlnJW2+q0sSGf8+UsOkULSYszvvY+b8GzNkilqP6nUnwT1O2O6GMb5HscoMI6fYsfBqtkPXvfi0h+hGopTQkjvf3EAUhbOswlz00pnR9U4jKLr1Ii/kmbRenDhCWmNFhmgsTRSqxA827cQR4fqX/NSL7Vn57RRyyY2ql+H3oKufpK0dN7g1NC3ep6paSsprqqxuDNu29I8rVfLqiHQeTU3PzQOb+llvExbfTci2n8ogzvYTNykuPBQ7kpxe3lzcyNiZPJsPdlD+RX5MXe6mZE7CPJW0YlHUEqNZvAYuESPXbBQsjR4QqZuRpbaTzzpwzlGoIHx++2cNCBcoFBE2L09O9SBdIlFF/OrP/9CEeIFEBfGPnpXsNKBd4VBB+uJAhypeoFBB+PL0QgPCBQoVhD+ffD7TgHEJQwXlmxMdyrhAoYTwlRaEr5QR/npzcn2rAeUKhxrSP2lB+SeFhHXoukoYiijr4GiXMH6LEY/iNy2WmAsLnfZ20+aom/icC5jZdND/rG40/FnAkNdBr84hF+B0d7N3KPOtBfjPHexwoml+Ovn87vjw4EQRia5KgWzUecACvNwudmXNV3zr/Xp2qar2lKpEolfoVQvxnHv4VTnIApxgQq0XvkdJrfVz9ygJtV4N+FKV8FqvCH6pS4fwi50VOw8WuhNj1pYcRXp+EZGM/TMxIR6DsNHBNrn7Z4lXXtWURK682tctYyNXiiMWaqpGD412E79hIy5jwJZ6YRaj1RPHTSLPelqYahOGgEgMcQcYpYS8UIQv00lIc21oBY9CVqidhI6rQ8NGXMaALfVatBgZEWZ5EhP9R/uh+3EU9qy5wnZMZA1Ci1pCKQ6x/epgcahrrkVxFM21C0KL4tDo0EUc+lIC7qRFqSLAtncnIcCzrEC1Sap41aZSKafTsIJYwsHUMVKxvNOpSD7YRm6onFWlVc5JQsu+Q5n9VbJq6JRX/ySc8hyrfvLOe+J6sMkSCYcKx2pfqVUar43rK2dV6JTGaRs5vqWcVaVVGq/8VsDEuldfEduq5TF8UF8bC53SOH2XOkenkPoubCpOYRUrHrUaOqVxSq21B8zrm/1H+D/l7HraJfOUdOafiaW8HACVHnQnrHp2pVZpvLIlhrZM9siGFJgPsRVFCxRaV7k8ll6UJGjyp55iU7Nup1ClHc3u9jfS1vEaVi/PahN0P7eTnZTigq3EjXYgtjw5G8TSqoPlSEggWFaBvlWqqlDoFd6tWNmjGYMNiEFgA/M+9FJpqUNGWA4iEc7b9kL7zswix0ol5CYYodpVLidhXrxMTS30yknkaS3DqdArhVO+OLgEq0qzFF5hZPnRIrwqzXKSHMoMqRlgJSx4hpy4MU6XaVq1ainM8GRKQoYWBma1ainM8HxqCV6lYmmsqnnUUuyaAOSwTNAFi4vQKzXLS//kH5qR+hbXV6/bFFXaFjSaG0hbDCCYu1wUKPQqnJOoZjmIRO6cRDXVrnJpc5IlaqrMsAI0N1iCU6FX4pxkCVZyQyVsW+Iu2lD9s+VtpCGEVmylMq5dYKHWUi+HocRAkCFm8oJB7FRivNggJXkhY5KDW4b6DKkBLiDYWXD0d+RGuQzR6wCQwnIpcjI5SQ7hGWAlN4xnKzUYZIiWzIAQ92AZP6rQK4nTMv18oVcOp2X8DFeef5GvFy9BqtIsJzBYZiDcACuZwXDfwTJdX6FXDqel+nOpAX5IOLrxMl1mItlWLyccR2b44gA1qSGMi/lMsVSfKYEcJCZgHeBVaZbEywfL9PKVZjm8Flp/SiSuPiW+u1AVLBRL2w9fhJTEsStZjJRUVvlW+yK8KtUSmZk7YDloy305hk0IMuMZlmBYq5YXz7AEL6mB6WqC0kfYSQ9Mz6MKFqFXapbC696SmNhjgFWhVwqnhyyWeGJngFSpWHbkiWpuffW/kSD9LHA3LnBMK3KfQXR+VQxSQ/QbNmmHHckK0K9zhvySminwYSW00iwGZgKJhBJj5KhM6UDkkZca60hlKivQsVaAEZhyI8Dp9Nra5dFEWyzq6RVa5dHKvKg4rKmeXEv3/4hIx1ZPK22Mbxq8NbjLCnYc61bVM6UDkdu/q2cqa+JH7GEXoNfWLoPmUgQVUKsHEfUlJysmgTB8qCfX0v0bmSolIEbWEDtNykOyfSuwtkKudF0k/WWLhDxHqSgAo6Wu7TL1kEjLquzqw50KRYvEk5R6qSIPaNsg0npBctm0+sMeEsX1chHuVCha1EsZk6I8+9kz781bJOT3aC117d68h0R6q9GAOxWKWvLmg3UHssh0A1fiKVZuQ3RhadGVUBqriiGuXUukd/PtcmoNcT0kiuvrOrRiR/oh0iFDsOFS3IfpY4nf9MifeABEeMb7DIf9Cru5s8rmLDtdSFl9auXV2D8MR4sqRCknqT2+27GM/KbdKJuqXfcgaFEeGi0TlWtizzL9XT2a1+jV7FyOpfwgAJK3dNpQpmRfk4O8gB3P57cd2C186QvaY2FABEDyaqMelNXwRLkGpF6CzkO3AUZZX7M48T6e38r+zVOSAt8D98B7BiMxiqZchxIvpmyYo8ocViiUc6Y48jO1bEqNcg7eep5aNoVCOWTqWzvUcmrplXPYUeoklsBJaqZL4EfSg0JJpDqKpR17waOP6l6vo1jO6Ykqsb5Sai21/yPmDOUwJm9xpGHm8thDoVBO7rlEdhQPiVFTqzx3QCmlUqM0d0Apm0KhHDKqi0ZqySi4DI3ISf5NaFEc2iCBY7L0QGIiQYJ2OS4c2Mo9gU5i11AqiRQEnboylzrItBpqpTncailJPHTe9HuVkuoolu5wqyXXVizZ4VZKTdgFWlRiDw+OxGPYJE6lxue2Dsj9Gf8H3SnNgxsDDw6K3POanqS1NzXSXPj6JGmG5QFza0Uo8F/wNQClBQ2ool6X7KibVRNpbNJULZ2GPtF80mLnQhmhnkLxjKA+NUwKRYIZqC0QuaWRpa6ngkWlRyD++gik9PrUVTWNhdhNsLlrbpTeE1c0oU5Jy5rVOltDlYQxoGg1MmJIqXR6OsXzUsNEBvb2sKKARk+hNEbqKhlBpSxWKulI4KG2ssmtacoKRFppZInoTQ8i/lKNFB9JAfxSjywfSS6FriqlPtLUz7pOlZU8BfYuDoMwS8wktO9AquncvTJ3jlKSA0ywR9shrrX/Bn3iLks5DYhk41aDqrU/yzblAz+MnyY3o1aJ+Jbnhba5zjYbIPqi2KpAcsBGXxev+UVZEMRxEOreD2GQkkoEy253PJW632C/k3OT09vkpkT9S6XlWfYqsCIE+g/OEKLpBimIA3T+LbVswVFjVbHm5mg3EbJysd4l0lHkhoDd5RrqMDcx/PUhjNVQHQMgnm7pq7vpkzKGHZ2yyhDVlm1soagCc2cFjic6dcJoIVIQyJgSIaV2DBwURWFJWwWnNcyO5t/gKEaounKGtMLEhc9M0KmyuaiiOIhAEmG15J6ta+LafiRmulOYI3KDraTuCWE1OmomGp0OXU616UGfUF9EFfnGjf0HKwZmFsHm6EwP+GjZsCMVN3NJ9aBLoPug0i2kchCFy6klbMQWrDrTR93+Ssv3dOqMSDi4gdLPhy4E1rQ9FxYhyXWX1GfAMQYpzgcbRhziTwz3FKdPEZC1xzDCuVKtgKZcP3CEqCiHcMFz0N0RVr5vXThlQhxqanLPMEhSK0hlNgCyMtE80KiCreRKbc0DGsUyymOJVTCpNYllsAuTYhFsY9mytkBbTPoaxTJyw1TuflQ7t3lLm1gm+L5fO/Skj34DGsUyQrcYK+3NegoF80mtNFNDpNIkloGyqiW8Rj24G9fM9cvF31G01DzoOUVbyF7/pwZazN8E0H3JeJ04speLWyEWHX0yNhqKolM2yaXHkEiY4I6RljwaDnGdPy4yUZQ5xAzQEzJvZ+zmlJObP9dcODph8vAzMhWTNOD0LxoUuRGgYMc87i1TLBivle5iYDlusBVVB8os3H7mpW4uHQhOrVSZsgJvDOhdyrJ4cu3bmTA3EdET6sG4D4/v949RP2YGdoRXAyQVVGmL4jlN87PsP63dul5D0XROgDoblNYcFgG6TBo6VLKCsJvGqI5U9lWLdQQiz0o3YayOVEenHDZmCWAJWi3lUk55ZEp5tZQK5YMGnqo7U0ipp1fwWaJmow2X6y9CCS2sWAYTf8MySx2cebmy1osi0s8Atu0q/TSgY6WW1EkzmU9brWhOMjfKKHxm7phRufiHSnnk6gRzCNXWrVBGnYruoHu/9aUdOyMyaSp9PqeAyVwknQdGANFAurNiBweSJSDNIqXM6BBEc/WsQEmeAwpPonoZHB2wcQPFI1JXsUQPWhUtgl5JrCRkUmbkJeY29J7/LHWrl8Roxp5vwUG/ZH5Mr468NPZz76rgIqhkxOcnZBjcuEzzhJkLWZTQgrWVuLaYA1ClBQwkuJyY0ZWw1zYKdJFHDenYp58n5Kmw8yaPNAM1DD65Q2lbphks0hEvozxloJ65900DP3+HewDztD1sClRRwZB0vHOCHymgZ64U0LFOWAsgQ5QAjhXWnJ6Gd++LQl5Uz5tvYtVChdEXPNwXV6ryjvYBSFGXU16hvMzAL+zIc3mvbIdV8zy3wEEfics9CVhn0K9ykfdViQFvgziFldu2UjhhT8N4RtZSZhZEnTPpyIStwsWa3/HVZ5TFm6LsB1s6dPc6AzGhfjSjNI6GC/OIkDAnkAu2kD8XphvN9YIYsDaVzAUsH60wqCJ8TAa84jzOYM7Bn3GkQj1Ptpd6FyYkDk/uRXL/zp+9kRpUUcGZ39vXsowmSoOibE49acXTJlkUhbGAijNKoK9Q67EL1nhnLdQsqClVUicXIJTg5vm7ZIBriJ6L8AjKOZKFsRI+vSEAD2oUjq8WOx3ZzDOcNGQTDmt2kT0JGAu7sJ7mDXyZOyMhIgVTIXPh0Y45aYeEeUwjPcL8sQ2nXqimLx3RWg8CHbiz61mdhKIneM6ILjBhyAhSPk91iVW4dWjFDu8aXL43usDSW36zMEQ8vZXhz6vd3fKOo1Km1s2rRjq5vrbY13c1FzInN6pKShFdksUzU1HRcfY1zOkKtpEbCrdpT+4chO6BLQNgS+wcfNGDLwNfS+y86ZuUAk5ElS906OJUShF3Jc9B+R2I73q6YnUdIvO4Oe4xknGc69t69gnPHHC5GcB8jnOa2806ovV5Wo7joj48T6o9Kz9KwbioVUTBTLWrh9H2EzeZf3y7ja8ndCK2+fsEHVy8WwKE0QoA8G7vYK5b3cbVEzoR2+zV/w4szoV+eksXBIi5Rk3tIOk/9E9uu9BVi6w4pV9Y0j+s+pCYkLainhZpQ1m5fgnXSSPUhq/XbfA0Cvi436ULn1BTWsJ+Sbhz1zKBLOXOxZeGkWvzxhUwIawlz8aIm60MiKXgOQhhQUy6T3YUYUvwDIStTK/5oYLyegzBkEc0CeOA0UjFXmkQhDnK1p6b7CRibmgQhDnJ1okdu2vRnSxVhyDcWaACeUeLIOxPLvB4V8t4UFfyxeCVh3QmxmRnOeGDadloYiG6Z+4Ln49Ugp/QkTwfYwxVx44kazaEz0YqBeFEZL8kvqiCLUXJWBcoc3VM3ZJj3mGgSZiQpKa/M4+De9CSQuSaD7EVRdxJGUi2L23T3IagK+POEdVmMSWTBCvoCeki+E+tiUgLQbJJnSWHb/7NYhw0I+8rEVGSk8+d8MGelXib0o5kIyfqkVIzJYYxQCJexnjxDWXMAnEc8h7pJdm4gGL05M6df4usCF2QfQVCVlwkAS1lC1p1kYSyli5m5UUWzBmrsYRFEgkoW8JnoPRC3vwRLPAKqZJWhsTjHdEmiIfMzoqqR9BsWirimTg7k17xUPsK5qOVWRlIKsSsA+CcXfIQt1QIWrmQClYMzjvAu3PHAbMQLm6NRRrShoIZaO9BnPBHjLHAbEieutoiDlQpTs7+bMmgv5jiQnAmw5JK/0LOGIA4DZcI9qyOwniwlkXhA5yVpq59h/LwmH7ozFmLb1rEKCm2M2EOKF08UIl9Hz4GSZjFNqCXXz/cqT7pPF5bem25dMdqIasI+Cub+8xUhdxoAjLGdYw0LSrkKHbv0elu1PMicfzd+zhkig5uyElqxRu082LaFhYkDChJMh+8X7MYmGvLS10f3aonFCBVNhdE20JSxcFqy+ODguuFYDg9mRMglTVUIKKGSC5A6IwFiMXaqC9zAiShNuqJ5AKEjkXjNJ3C8HQl8tkHL8o2O2qBhqLKngFRbFHSRHMB9J8ccH/npt1hTgjEAeGTQAq1H0HolKJ1tkiq0AGIJpkLHrAicYgawmggeKcLu9Qfz8HYYuSFW+7z1TUfpM+oRHCZcgc86KeHscd7LqGjvS2HC0IUh/cuku8GvGuyHRBdSaLKM0x3o3myOqTcwAGPK4RqMiWs1WgL4mZE+IH0qD/h9SM4wXPTJzT5Ng/2Dg5X+werfYIR+OMWBJ0PmXFuIg19l56KuNoZ7RyKqL6aFqu+dukzOIrK4pM5Jy/C5GDszgaKctL3k5C4DVGw0pupldyZMdi6STqQOJmMalTW1JMgDpwMeVaS5OPC0EIazVxkEVMtNhsQVcY0C0EpYGAJgtZmqq+mlsukmjuvvqLvI/iMt262vpuqOaZvjFC1xlN3OtBaXRoPjbsUnfVXE7V6sMFyKy0/msp08IgclSnb+bdpsSrTzzj2emfaWm6XV7FGS/peQu/Oh2pU1qy+i9NC9VfT2zL6Rwoe6fdr0Uqn8+2sts2pu/5qotanBCW4pgcl0/Q2vpvTq/CqLT9SuqN0enlzccPr8Z7CWjFtG+mCIyaOaN28XbIPjJifgQAbhW6jL2Lyefpc1NiO5zgYzp1NIpb0V3Q4CTZUhvGMAKT9+UyLbG2GWQ3VGsXX0zHgTmvg0q5BCI2PJyPwo8y0Yv/+eBKE1tcL5+K6vv1yc7BoW4djMKsVMdhOZSo+n1yUYYK3jadBaHwsOx/RDV6tmW5sCBUOfBjt6MDVpJrrNdqfL76vTjGS7zqOB9D9YLxD3tZz19OageOPZeUa/txNoN3pZ+8ZixeiMH3gezb9CGFVvLWVDETbgN8aBQyjLUfqYZEu/vEmSATui01JM7d+ENmt/Yi/WPA/ii8nd29IyETV5aezdKOlRd+ayr4jYR4S241tjx6LxICkljAPiecGs3CU389DEYXe05ZlQk8H0hAxD0sM7NQKtvOKpyVkHh7WGS0dDN/sltprcPeJVa8xxynCTX+a6vLTmW019AYORrE01VKA7IFhAydVfMdf+2yRDDOw4jh8MI8e3/FXOwzCoMmaVxS5QKjV8sx3QsC1ZIkAl/lrEJv7R48HewLgdaQJr0DtEAN/5KQVFXfzywnLWLCLwAk6+RU3v5yiOPKRnSforT9UuoQGveFR30/UgjssVHvomqTKOBgUXlpsfKJR1sAS1Wgp50TQJkjjkwnVqvja3IIAxCyb7j3FzU/VRv1Pu18NzcfB1KwNc8P9sW7TDVyGdfAy9Xb+UWMZviliZmZWJOoOxAGgJ7Ziw1MLke05zE3g3jTgaG3vcK4TzzZFiCuDeXhqIQuvjiYeABFOs7BQM6v0c9Tq6pt656kpZUYhuw1R5m7gpPA4KJIo7RtcbccpxKvogqYUQaUxA1BXzOJru+xnptABffboP5ZMp5RP552ty7uzOYvEPKlGBurMSDwiMmfr8F113i5nUB/Y5IpQHABkx2GGrj2aD6kpaSYoB0QxQDHbjumADRobB4+9M0Oky50JGNyj0wtbaIFIAMyutJngPkI1aCdpPrCmpJmgBqPCmAHxhIkNgPFBklhbYK6zzWagJ2eG1Zc3F2CUmfjq6uGVCnaAPXkCABZp2ATBa0qbCQ5dCmitPQF9XFPSXFBx+AvshARYqylpJqjvGcgEmKkSMxNOAvxoJ6A91nLmAkotG11gCsc6AQXXlTYT3A0SdykIW0fYbLvFwPKF9a89cXOTBVoJPfyEGVUpRUTmQgElWMtRmXCy7CEnOModSZfAv7SCLbcgolF3wIrMN9Qp/KhRS1pGgcqoBXIXN6+NKfb5+fR0sm06ok6uL83Ty8OPE+URLY5v4p1vb8jSKOEZpUxek4/AxD3w9AZHx1oJngZ4ak3hbsQzI4eqmd/k4m5KmLwe05o2TYbSlTIZzmCE+igMtlD1AfW5DzZZf/X59OWx1iA9GUhPzPTwbTg+z6gY1efTAeQj8nQE1fey12lxYO+c5TLuWFmiwer4Yn6b4W/L2NmWIJXuEH+ENtEQJavBUO0xW5Qh011hM/3VSpwfhSF9Q4IbXSVOSnlpsn6+s2JnMFi6H60cu/cMKQq6Ydk4oFjNFlrncy/Z23+zPnZ2e2/mNgN0YTQmYhbB0tTaVtrVyM1l5J/hna8GHoMo8DdR34ipH9pbEVEZE+y5wR1wUFO2vARw5bAAj5YfeSjbS+BGEUgT48GzAhN5w9CjM8ONuQ4fTQf4oVHoM+iIfMsNlEIqFQ5ggp+Zqi3V0DmADCWdUg6tqXQAG3pjp7hu7UbLMb8NWymwttqx0lwAYEfvAEIv3IbFSYBEKcSu4gGMcKrg+GCFzgMpg9fQ2UIGHrFD41xZ6e6Pda6f/HXj5PwSTjKtaLe/ioLtD0brbX4pB3OknH+8Ps15mydXeOIpRhhqlWIkQbvXV9mHsSCpqPhEiQoDIEgUQDnNo+ROkDjUwNEx+Cpb1gyxl/91e2umIEnzdH2zqm5H1qwK3JH1RqCsQ4Gy3gqUdSRQ1vEcWWG4Ru3ITEJ7phgTBf9un9DGNOrVY/N75tp3pmXD1xLRslHu3ln9HBKawhlqAqcOFhyi0IAgRh4chXACpznCsjTK5tHDEsz7fXNPhJiDeWJuqiR1gsaWPNePCWd+szqxhpjZpmrJmmmvWtasfrUhRiC9Wd1zLWZWz1yLmdUpF2Ki2A2gk5KlaRjAP2B3BRxhYstgohjYwL0XKRhfT5O3J4Ficc+ajbTOYpMaPe555SieBfngHX966JNJF0xIk0+4b0+ILpRQB/qZ6LAcDt6yQw/P32QocEAeq1zcX4mueYCvxgBd7oBmtTJ0lgHS68RB7sQdSBVpyW+xyP9QYUjfzoqFyWL12yyWKfO0H2f5HxcCq+lEQKp1l8u2ZvmgWLdVVMEZoRT/ab7fP5ZVOVHfLLPyl9d/+lYAx5Z4CQPHoV9We4Xa0TFDw9650RKUIxC70Q7EllfVKgko1iGsuhLHnmHT4mUaxSrLLJ6qyzML4OgLHHQJ9RLqy8Zse6G9aFMu7aCmfrOaJb+RSrFZKh/JSp4CexeHQQg9Y3neDPcwls9SlJsDxHEQKteaeGagzu6VWtf2I6UKN27s41LOom1sqfEZa7bII5LkrwyXrtJW1eSrtifZreuLTpfsUNsHV5WjwCfTPXCfx7gLUV+vZDhgY2UeyiMkVGz7gkChovOrZ4SKLG4/EVuuk90zQpr2qRL6KWDnSWrlIJ0qipBLUZCoqWKqhCycAljPpAgT2woZFA2WGM8vqpAnFA9bLNtUgP00ILMlDQ0T+EjEWXX4+lsdMfzpwry5eL//d/Py9Kt5+eWv5vWXS/Pk6sK8/WJ+/HRy82d2SYWgq+uLz7fm2U8/m5++/Mz8NdR4+fXTLUTz6eSv58yfXfzt5/f7x5f7+/uXP9/+dMJL+xiHp9xbXoae7nN//tPePAG52c8/n/z06Tw3t/nTyc35mXn+9/PTr7cXXz4Lkf/32/PrzyefzE9nsFC/XJtXN9cnl3MlF6jh/3FXkeLTTxe3t/Bf55/PLk4+T6N2+uXy8svnwnSXX87ORdjr9Mvnjxc/m9cnZxdfzJ++nFyf4VIx/3p+LUk8lHwwVXQh4vPJZZv8//c9C9P/89P12eGbN+9O8r+4pV6f/5Ug9GTvgFMeaizm5fnlp9OzCTXt8qfzszPYKnAExemni/PPtxxMPp/fonpy9eUz/M68+Hz66SsUxirANG9uT24vTuGHny4+t02MduBcGz5wA5SallXk6acvp39BHe3Z9QUsedhjnt9wUPr66ermxpwppGqLeTlffL5g/xR2HrhBtGyx97hnf/3EJePm4v91ZRxs7L09DjGwjpzCVg+tcXJzc/Hx4vQEdZrm2cXNCVfHROiOL64uv6KR8Ia5WK9Pp5fH7cUl/Gjy52fnP339uUA+rSPJJXw9ub6d9n1htVwM7Im/TgVS1cy800AVBXYcRa85UyRsx3/5dA5bTz5UMLa3s8sTAQ3t4uDUhJJ46uTfLq7PMdy6+6q0zxuHvnz8+OnLyRnqG//25fovqI87/QtXbz7ZYfjC3KDazRJ6lefXH09Omcvt9gTWxvMr6FGifzY9BX4AN7CzPb/lRs5hJRN26ybuBXiKAbrbn05uoU831Z3L2f3j5vr2dG7dKgzNxcE0/3Z+8peWRtO00jR211kKTPP3v38A1t0f/sAq7+rTJwFN9erL3+DXlyefT36G//56ap789eTiE9+IAhvvx4sZfgeLY7e3dyDasTvmk5dvPH7+Cgfzs7+Yt3++PoedCvRM4GTj5vbLNbQfNCZuuTctdQccgGsbwtH9BE4qJ5Rr7iRUgj5en5+j1STzL3BidP6pBa06Clmmr5uq5PTLdbvgbHy92FRxuHUVjashtJmqsyXac9exFT99bCcPt7tLA8TXgjB56q6cEl9kkuZ3XkIBt1+igi/64wIdF6mfrjJ7hf6yd5YbYLIhfj702sqOsq6xU/D42j9UoXzTUb6J7g9fJ93dKDmqvdBKTWvttmtFuEk3U/Tj0zvxsPL8neJfN3bsRmlL+e/KWEIrS8MtCIz8TRQCbt6Epyuvu+LKAqy8124YWnX73SYLcDx3GdedtBCmcdZtiRIwOFZqCdXPUTiBFYSmbcL2uATz0HdTcxPD5m9GId5FWwAENAB4tEG0VPFD/XGauooLHidzt1JwaUW4F1bP20bByIFjxU67Q95/p0D34yNF+//+3z1vXIL+BytGx72SleV5C5i+Ug8e09haEkAEHCtAi2OtYTE/EaquEGJggjgO42QJGOgN3/0V3wvfHpzdX1WMPmCdbU28c9/SXuy5MwHwrTuAhm1oSX+Fri9NrXgL0i4Cyms9n+y1D5/8yOeZzYSQ7jJ/3QFRPJOvvOsWvvbhkx8L5/C1s3+kBATRQYRQ0PPX8PmPHM5iT0nd847iqV+lDRGvk9T5kXWcGJAfRRxgUFoF2qiRA2IeOgRDIjkQrzdB+Dp/ugggikeFYTV/U1eXyt7e7A65r/+Gn6g1k1w0k+zS9wVe/614tpBtpCHisQ91eH79ZXb95bWMTCw8NqHPWF9v0G+v69/UGkgZMB5rDa8xvN6Uvy9mNeUAudrf8BrB6w164TV+4XX1guJmqR4iV2ulePivuyeB5DdPwUjI6x2U1+gLkfPWH2eiwitwvfW319DzB3byI/p1hf9TBZZyUcjM/zZ9K2qj+nsh79uL15dW9OPvfv/l6+3V11vz7OL6D8bvfn91/eX/np/eoq2oP6zwxwyY83DFleuAVbEg3IWbB5+bYdSdHz9s3+8f+/v7+/42XU/0CigWchNSXkUs9JObpJXgyjQZ/CM/ZL8x8ZypDWf0+795r16/ht4x8n5exw+PsLPd+iDoBr2PykEetpeGU7RvbVoPb9TG5DDxLkzS52hjPrqwh1vl5yJwHU7cNwd5z+ekq/x8m7POXM/BmzGrbZCtqva2torMZw2rNMTV767yF2CXtPGsLSn57/JWm1YzpdsaDjsc1i7eLu39P9va1MF8fkseWuGT1MWNjagz+zhNbCOU5ZSurXL4mDq31io4bHDIWit80gmlOnzudWr0e2LC8yGURb6h1x4Itunuxz31nSlX+Tbf/08JKy/hXgduJQnw10J6qUf4RyXu9YOb7l7j+aCOjhSvONuN7cyzYgdEIHBAYD9N2yPVh1EAhymnN8tk3+Gc43gJoFE7cRxF80OZrAz/9eKHPz36HnoVxOhELHx5f5Wfy4JSQscNtvDR19uPr999e/mnXEA5H61v1LVXfuhksEUlAKVRKzZJb0Ca4p3kTvrhFY6jg59DQRGI06cbG/77x/x+QTzRNeRhO8UHc6/y165g+f+EjcoNsVk52gmdu6ISL8r3UFHxQYNU5QEflUsLDrn9RBAfLvSbFER//N3v0aliC5Zv/AcErfwR/nced/q73xfw/tDN+IxBFMGp3168fh1ZaNktxWsWWIbpuPGHUgp+Ah/8IX8Aa0wLh6JaNL+MJFajzC7gzaw5nYsnijU30pjTfRUWKd4ITocu4mhVzJUd22XedDu2p9XJcggbvr2hXT1evnp5c3F59eni9OL2H+bN7Vd0du/q+svV+fXtxfnNyw8v//Xt5VkZWfHhG/zz27eXiXUPYIUL7bu/WrGLTjcn6PEH9A/0Avof7DUjF77l3H0K7XwDqPjhQ/kfSZWHFSU6NA/2Dg5X+wer/fL3V+V/oJPVXyKSgM6CWvH83/k/oIBuk39+HP4NiyiHgcLeElgi/4RFUtUEKAnVhFdVLcYnqxHLcpE48cwqf4IJWaD0wijxPTJO7G7dwPKqb/DTojHCB/uvcCR8Cr+Efx0cHrw/Pj7aO/r3qw4CPCwTIIzkqZ+A4fjg6O3e28OD6RD6GeUnwHh3dLz/fv/N8Z4QHGXm+AlAXr8/2nt39GZPjEGayeKngNk/3Dt6//bw3bvpaEhJ4SdA2T98B+2y/+7oUBiUNxOhHB3tH759c3T8VhiSt5PL5+jo7f572IBmNGFS5vgpBXS0f/Tm/fvDN++FQTmebJa9/XdvYafyZn86lk7i+kkw3uwfH799u39wPAvGaOL7KaX17mjv8D2004xKXGeRn1Rd3h29fb9/dDyja+kkoZ9WUw7f7r892j+Y0YA6SewnwTg4Pnx/eHw4Z/yhJsGfBOjdu4O3sO6+nVE/Okn0p8A4fn/05u3BwfGMdkzKwT9pXD48eAuBiIFyMNVNeXfw5t3x+zczqkkn0f4UUxzsvTl+/25/Rq/Wya8/BQRsL28PD9+/nzHcjKTnn1I+b9+/ge7SnGY8mtx/iqO/d/Tu7cHhmwNRxurfDTCtHr2HsA72j97++79f/vv/BzUe2j4==END_SIMPLICITY_STUDIO_METADATA
